# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  setup_ec2:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "47:ef:5a:b5:a8:3f:ca:57:7e:39:ec:27:70:96:88:1b"
      - run:
          name: Install Dependencies
          command: |
            apk add --update ansible #Install dependencies for the playbook

      - run: ssh-keyscan 52.66.79.227 >> ~/.ssh/known_hosts 

      - run:
          name: Setup the Server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

workflows:
  # Name the workflow 
  my_workflow:
    jobs:
      - setup_ec2
